//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhotoViewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   About Photo Viewer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CAPTION_ABOUT {
            get {
                return ResourceManager.GetString("CAPTION_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CAPTION_ERROR {
            get {
                return ResourceManager.GetString("CAPTION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JPEG (*.jpg;*.jpeg;*.jpe;*.jfif)|*.jpg;*.jpeg;*.jpe;*.jfif|TIFF (*.tif;*.tiff)|*.tif;*.tiff|PNG (*.png)|*.png|All Files (*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FILE_FILTER {
            get {
                return ResourceManager.GetString("FILE_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FILE_VERSION {
            get {
                return ResourceManager.GetString("FILE_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ctrl+C に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GESTURE_COPY {
            get {
                return ResourceManager.GetString("GESTURE_COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GESTURE_DELETE {
            get {
                return ResourceManager.GetString("GESTURE_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alt+F4 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GESTURE_EXIT {
            get {
                return ResourceManager.GetString("GESTURE_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   F1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GESTURE_HELP_TOPICS {
            get {
                return ResourceManager.GetString("GESTURE_HELP_TOPICS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GESTURE_NEXT {
            get {
                return ResourceManager.GetString("GESTURE_NEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ctrl+O に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GESTURE_OPEN {
            get {
                return ResourceManager.GetString("GESTURE_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Left に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GESTURE_PREVIOUS {
            get {
                return ResourceManager.GetString("GESTURE_PREVIOUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _About Photo Viewer... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MENU_ABOUT {
            get {
                return ResourceManager.GetString("MENU_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Copy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MENU_COPY {
            get {
                return ResourceManager.GetString("MENU_COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MENU_DELETE {
            get {
                return ResourceManager.GetString("MENU_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Edit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MENU_EDIT {
            get {
                return ResourceManager.GetString("MENU_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_xit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MENU_EXIT {
            get {
                return ResourceManager.GetString("MENU_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MENU_FILE {
            get {
                return ResourceManager.GetString("MENU_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _GitHub に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MENU_GITHUB {
            get {
                return ResourceManager.GetString("MENU_GITHUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Help に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MENU_HELP {
            get {
                return ResourceManager.GetString("MENU_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Help Topics に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MENU_HELP_TOPICS {
            get {
                return ResourceManager.GetString("MENU_HELP_TOPICS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Next に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MENU_NEXT {
            get {
                return ResourceManager.GetString("MENU_NEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Open... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MENU_OPEN {
            get {
                return ResourceManager.GetString("MENU_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open wit_h に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MENU_OPEN_FILE_WITH {
            get {
                return ResourceManager.GetString("MENU_OPEN_FILE_WITH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Previous に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MENU_PREVIOUS {
            get {
                return ResourceManager.GetString("MENU_PREVIOUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy (Ctrl+C) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TOOLTIP_COPY {
            get {
                return ResourceManager.GetString("TOOLTIP_COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete (Delete) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TOOLTIP_DELETE {
            get {
                return ResourceManager.GetString("TOOLTIP_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Next (Right) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TOOLTIP_NEXT {
            get {
                return ResourceManager.GetString("TOOLTIP_NEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open (Ctrl+O) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TOOLTIP_OPEN {
            get {
                return ResourceManager.GetString("TOOLTIP_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open with に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TOOLTIP_OPEN_FILE_WITH {
            get {
                return ResourceManager.GetString("TOOLTIP_OPEN_FILE_WITH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Previous (Left) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TOOLTIP_PREVIOUS {
            get {
                return ResourceManager.GetString("TOOLTIP_PREVIOUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://github.com/msl-ltd/PhotoViewer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string URL_GITHUB {
            get {
                return ResourceManager.GetString("URL_GITHUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://github.com/msl-ltd/PhotoViewer/wiki に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string URL_HELP_TOPICS {
            get {
                return ResourceManager.GetString("URL_HELP_TOPICS", resourceCulture);
            }
        }
    }
}
